title: "ترجمه‌ی خط فرمان لینوکس | وەرگێڕانی هێڵی فەرمانی لینوکس"
description: "ترجمه‌ی فارسی و کوردی-سورانی کتاب The Linux Command Line نوشته‌ی William Shotts"
baseurl: "/tlcl-translation"
url: "https://nonnoqteh.github.io"

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
  - scope:
      path: "fa/chapters"
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "ckb/chapters"
      type: "pages"
    values:
      layout: "default"
